apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: amrish24/vproapp:latest
        ports:
        - containerPort: 8080
          name: vproapp-port
      initContainers:
      - name: init-app1
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb.default.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-app2
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprocache01.default.svc.cluster.local; do echo waiting for mc; sleep 2; done;']
