apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache01
  labels:
    app: vprocache01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprocache01
  template:
    metadata:
      labels:
        app: vprocache01
    spec:
      containers:
      - name: vprocache01
        image: memcached
        ports:
        - containerPort: 11211
          name: vprocache-port
